---
title: "L'usage des réseaux sociaux comme source principale d'infomation réduit-il la confiance accordée aux médias traditionnels selon les générations."
author: "GUIRASSY Bafodé, NEUBAUER Noé"
output: html_document
date: " "
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r packages, message = FALSE, warning = FALSE}
library(dplyr)
library(ggplot2)
```

```{r import}
data <- read.table("data/les-francais-et-l-information-arcom-2024-base-anonymisee.txt", quote ="",
                   header = TRUE, 
                   sep = "\t")
```

# Recodage variables

```{r fonction recode_age}
recode_age <-function(x){
  if(sum(!(x[!is.na(x)]%in% 1:7))==0){
    ordered(x,
            levels = c(1,2,3,4,5,6,7),
              labels = c("15-17 ans","18-24 ans", "25-34 ans",
                         "35-44 ans", "45-59 ans","60-69 ans",
                         "70 ans et +"))
  }
}
```


```{r fonction recode_confiance}
recode_confiance<-function(x){
  if(sum(!(x[!is.na(x)]%in%1:4))==0){
    ordered(x,
            levels=c(1,2,3,4),
            labels=c("Tout à fait confiance","Plutôt confiance","Plutôt pas confiance","Pas du tout confiance"))
  }
}

```
 


## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
